import {SiteCopy} from "../components/SiteCopy";
import {cookies,headers} from "next/headers";
import {LanguageProvider} from "../components/LanguageProvider";
import {parseLanguage,preferredLanguage,languageTag} from "../data/languages";
import type { Metadata } from "next";

import { AmbientBackground } from "../components/AmbientBackground";
import { Header } from "../components/Header";
import { CartProvider } from "../components/CartProvider";
import "./globals.css";
import "./responsive.css";
import "./languages.css";
import "./selects.css";
import "./type-scale.css";
import "./requests.css";
import {SiteProvider} from "../components/SiteProvider";
import {readContent} from "../lib/cms-store";
import {isAdmin} from "../lib/admin-auth";
export const metadata: Metadata={ metadataBase:new URL("https://arxylve.com"), applicationName:"ARXYLVE", title:{default:"ARXYLVE — Sculptures miroir",template:"%s — ARXYLVE"}, description:"Sculptures miroir en résine colorée et en béton par Alexy Mekerke. Découvrez la collection ARXYLVE et les projets sur mesure." };
export default async function RootLayout({children}:{children:React.ReactNode}){const [content,admin]=await Promise.all([readContent(),isAdmin()]);const [cookieJar,requestHeaders]=await Promise.all([cookies(),headers()]);const language=parseLanguage(cookieJar.get("arxylve-language")?.value)??preferredLanguage(requestHeaders.get("accept-language"));return <html lang={languageTag[language]}><body><AmbientBackground/><LanguageProvider initial={language}><SiteProvider initial={content} admin={admin}><a className="skip-link" href="#contenu"><SiteCopy id="Shared.skip" fallback="Aller au contenu"/></a><CartProvider><Header />{children}</CartProvider></SiteProvider></LanguageProvider></body></html>};
