"use client";
import {RequestInbox} from "./RequestInbox";
import {LiquidSelect} from "./LiquidSelect";
import {saveAndSignOut} from "../lib/admin-exit";
import {VisualEditor} from "./VisualEditor";
import {EditionAdmin} from "./EditionAdmin";
import {DeviceSettings} from "./DeviceSettings";
import Image from 'next/image';import {useEffect,useRef,useState} from 'react';import {initialContent,type SiteContent} from '../data/content';import {statusLabels,type Sculpture} from '../data/sculptures';
export function AdminPanel(){
 const exiting=useRef(false),leaving=useRef(false);const [mediaBusy,setMediaBusy]=useState(false);const [auth,setAuth]=useState<boolean|null>(null),[configured,setConfigured]=useState(true),[password,setPassword]=useState(''),[setup,setSetup]=useState(''),[pairing,setPairing]=useState(''),[deviceName,setDeviceName]=useState('Mon appareil'),[content,setContent]=useState<SiteContent>(initialContent),[index,setIndex]=useState(0),[tab,setTab]=useState('works'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1)),token=params.get('setup'),pair=params.get('device');if(token||pair){history.replaceState(null,'',location.pathname)}fetch('/api/admin/session').then(r=>r.json()).then(async data=>{if(token)setSetup(token);if(pair)setPairing(pair);if(data.needsTrust){const trust=await fetch('/api/admin/devices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'trust',name:'Mon ordinateur'})});if(!trust.ok)throw Error('Impossible d’autoriser cet appareil.');location.reload();return}setAuth(data.admin);setConfigured(data.configured);if(data.admin){const r=await fetch('/api/admin/content');if(!r.ok)throw Error('Session expirée.');setContent(await r.json())}}).catch(()=>setMessage('Impossible de charger l’administration.'))},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{if(leaving.current)return;e.preventDefault();e.returnValue=''};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty]);
 function edit(next:SiteContent){setContent(next);setDirty(true);setMessage('')}
 const selected=content.sculptures[index];function work(change:Partial<Sculpture>){edit({...content,sculptures:content.sculptures.map((s,i)=>i===index?{...s,...change}:s)})}
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const r=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,setup,pairing,name:deviceName})}),data=await r.json();if(!r.ok)throw Error(data.message);location.replace('/admin')}catch(e){setMessage((e as Error).message);setBusy(false)}}
 async function exitAdmin(){if(busy||mediaBusy||exiting.current)return;exiting.current=true;setBusy(true);setMessage(dirty?'Enregistrement et retour à l’accueil…':'Déconnexion et retour à l’accueil…');try{await saveAndSignOut(dirty?content:null,saved=>{setContent(saved);setDirty(false)});leaving.current=true;location.replace('/')}catch(e){setMessage(e instanceof Error?e.message:'Impossible de quitter l’administration. Réessayez.');exiting.current=false;setBusy(false)}}
 async function upload(files:FileList|null,kind:'main'|'photos'|'videos'|'portrait'|'about'){if(!files?.length)return;setBusy(true);setMessage('Import en cours…');try{const uploaded:{src:string;alt:string;video:boolean}[]=[];for(const file of Array.from(files)){const form=new FormData();form.set('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:form}),data=await r.json();if(!r.ok)throw Error(data.message);if((kind==='videos')!==data.video)throw Error('Choisissez le bon type de média.');uploaded.push({...data,alt:file.name.replace(/\.[^.]+$/,'')})}if(kind==='about')edit({...content,aboutPhotos:[...(content.aboutPhotos??[]),...uploaded.map(({src,alt})=>({src,alt}))]});else if(kind==='portrait')edit({...content,texts:{...content.texts,aboutPortrait:uploaded[0].src}});else if(kind==='main')work({image:uploaded[0].src,imageAlt:uploaded[0].alt,provisionalImage:false});else if(kind==='photos')work({photos:[...(selected.photos??[]),...uploaded.map(({src,alt})=>({src,alt}))]});else work({videos:[...(selected.videos??[]),...uploaded.map(({src,alt})=>({src,alt}))]});setMessage('Médias importés. Cliquez sur ARXYLVE pour enregistrer et quitter.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 if(auth===null)return <p>{message||'Chargement…'}</p>;
 if(!auth)return <form className="admin-login" onSubmit={login}><h1>{configured?'Administration':'Créer votre accès admin'}</h1><p>{configured?'Connectez-vous pour modifier votre site.':'Définissez votre mot de passe personnel (12 caractères minimum).'}</p>{!configured&&!setup&&<p>Ouvrez le raccourci « Administration ARXYLVE » créé dans le dossier du site pour initialiser votre accès.</p>}<label>Mot de passe<input type="password" autoComplete={configured?'current-password':'new-password'} minLength={configured?1:12} maxLength={200} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Nom de cet appareil<input value={deviceName} onChange={e=>setDeviceName(e.target.value)} maxLength={80}/></label>{configured&&<details><summary>Autoriser un nouveau navigateur</summary><label>Code d’invitation<input value={pairing} onChange={e=>setPairing(e.target.value)} autoComplete="off"/></label><p>Créez une invitation depuis un appareil déjà connecté.</p></details>}<button className="button" disabled={busy||(!configured&&!setup)}>{configured?'Se connecter':'Créer mon accès'}</button><p role="alert">{message}</p></form>;
 return <><div className="admin-command-bar"><button type="button" className="brand-button" onClick={exitAdmin} disabled={busy||mediaBusy} aria-label="Enregistrer, se déconnecter et revenir à l’accueil" title="Enregistrer et revenir à l’accueil">ARXYLVE</button><nav className="admin-main-nav" aria-label="Navigation de l’administration">{[{id:'requests',label:'Demandes'},{id:'works',label:'Œuvres et médias'},{id:'devices',label:'Appareils autorisés'},{id:'visual',label:'Éditeur du site'}].map(item=><button type="button" key={item.id} aria-current={tab===item.id?'page':undefined} disabled={busy||mediaBusy} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav></div><p role="status" className="admin-status">{message||(dirty?'Modifications non enregistrées. Cliquez sur ARXYLVE pour enregistrer et quitter.':'Toutes les modifications sont enregistrées.')}</p>
 <fieldset disabled={busy||mediaBusy} className="admin-editor">{tab==='works'?<><aside><button className="button" onClick={()=>{const slug='sculpture-'+Date.now();edit({...content,sculptures:[...content.sculptures,{slug,title:'Nouvelle sculpture',description:'',material:'',dimensions:'',image:'/images/test.jpg',imageAlt:'Visuel provisoire',provisionalImage:true,price:null,status:'unavailable',editionType:'unique',editionLabel:'Pièce unique',photos:[],videos:[]}]});setIndex(content.sculptures.length)}}>Ajouter une œuvre</button>{content.sculptures.map((s,i)=><button key={s.slug} className="admin-work-tab" aria-pressed={i===index} onClick={()=>setIndex(i)}>{s.title}</button>)}</aside>{selected&&<section className="admin-work"><h2>{selected.title}</h2><div className="admin-fields">{(['title','description','material','dimensions','editionLabel','imageAlt'] as const).map(key=><label key={key}>{{title:'Titre',description:'Description',material:'Matière',dimensions:'Dimensions',editionLabel:'Présentation de l’édition',imageAlt:'Description de l’image principale'}[key]}<textarea rows={key==='description'?4:2} value={selected[key]} onChange={e=>work({[key]:e.target.value})}/></label>)}<label>Prix (€ ; vide = sur demande)<input type="number" min="0" step="0.01" value={selected.price??''} onChange={e=>work({price:e.target.value===''?null:Number(e.target.value)})}/></label><label>État<LiquidSelect value={selected.status} onChange={e=>work({status:e.target.value as Sculpture['status']})}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</LiquidSelect></label><label>Type d’édition<LiquidSelect value={selected.editionType} onChange={e=>work({editionType:e.target.value as Sculpture['editionType'],...(e.target.value==='limited-numbered'?{totalEdition:selected.totalEdition??1,availableNumbers:selected.availableNumbers??[1]}:{availableNumbers:undefined})})}>{Object.entries({'limited-numbered':'Limitée et numérotée',unique:'Pièce unique','continuous-series':'Série continue','made-to-order':'Sur commande',prototype:'Prototype','exhibition-piece':'Pièce d’exposition'}).map(([v,label])=><option key={v} value={v}>{label}</option>)}</LiquidSelect></label>{selected.editionType==='limited-numbered'&&<EditionAdmin key={selected.slug} sculpture={selected} onChange={work}/>}</div>
 <h3>Photographie principale</h3><Image unoptimized width={220} height={200} className="admin-thumbnail" src={selected.image} alt={selected.imageAlt}/><label className="admin-upload">Remplacer l’image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files,'main')}/></label>
 <h3>Autres photographies</h3><p>24 photos supplémentaires maximum, de proportions libres. Les 6 premières apparaissent aussi à l’accueil.</p><div className="admin-media">{selected.photos?.map((p,i)=><div key={p.src+i}><Image unoptimized width={220} height={160} src={p.src} alt={p.alt}/><label>Description<input value={p.alt} onChange={e=>work({photos:selected.photos?.map((v,n)=>n===i?{...v,alt:e.target.value}:v)})}/></label><label>Format à l’accueil<LiquidSelect value={p.format??'original'} onChange={e=>work({photos:selected.photos?.map((v,n)=>n===i?{...v,format:e.target.value as 'original'|'square'|'vertical'|'horizontal'}:v)})}><option value="original">Original</option><option value="square">Carré · 1:1</option><option value="vertical">Vertical · 2:3</option><option value="horizontal">Horizontal · 3:2</option></LiquidSelect></label><button className="button" onClick={()=>work({photos:selected.photos?.filter((_,n)=>n!==i)})}>Retirer</button></div>)}</div><label className="admin-upload">Ajouter des photos (les 6 premières apparaissent à l’accueil)<input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files,'photos')}/></label>
 <h3>Vidéos</h3><p>12 vidéos MP4 ou WebM maximum, de proportions libres, sélectionnables dans la galerie de la fiche œuvre.</p><div className="admin-media">{selected.videos?.map((v,i)=><div key={v.src+i}><video controls preload="metadata" src={v.src}/><label>Légende<input value={v.alt} onChange={e=>work({videos:selected.videos?.map((p,n)=>n===i?{...p,alt:e.target.value}:p)})}/></label><button className="button" onClick={()=>work({videos:selected.videos?.filter((_,n)=>n!==i)})}>Retirer</button></div>)}</div><label className="admin-upload">Ajouter des vidéos MP4 ou WebM<input type="file" multiple accept="video/mp4,video/webm" onChange={e=>void upload(e.target.files,'videos')}/></label><button className="button" onClick={()=>{if(confirm('Retirer cette œuvre du catalogue ?')){edit({...content,sculptures:content.sculptures.filter((_,i)=>i!==index)});setIndex(0)}}}>Retirer l’œuvre du site</button></section>}</>:tab==='requests'?<RequestInbox/>:tab==='devices'?<DeviceSettings/>:<VisualEditor content={content} onChange={edit} busy={busy} onBusyChange={setMediaBusy}/>}</fieldset></>
}
