"use client";
import {SiteCopy,useCopy} from "./SiteCopy";
import {useLocalizedSite as useSite} from "./useLocalizedSite";
import Link from "next/link";
import {useState} from "react";
import Image from "next/image";
import {useCart} from "./CartProvider";
import {InquiryForm} from "./InquiryForm";
import {formatPrice,selectionKey,editionName} from "../data/sculptures";
export function CartPage(){const t=useCopy();const {content}=useSite();const sculptures=content.sculptures;const [compact,setCompact]=useState(false);const {items,ready,remove}=useCart();const selected=items.flatMap(item=>{const sculpture=sculptures.find(s=>s.slug===item.slug);return sculpture?[{...item,sculpture}]:[]});const total=selected.reduce((sum,item)=>sum+(item.sculpture.price??0),0);
return <main id="contenu" className="section cart-page" data-empty={ready&&!selected.length} data-compact={compact} onScrollCapture={e=>{if((e.target as HTMLElement).scrollTop>12)setCompact(true)}} onWheelCapture={e=>{if(e.deltaY>10)setCompact(true);else if(e.deltaY<0){const area=(e.target as HTMLElement).closest(".cart-selection, .cart-layout>div:last-child, .cart-layout") as HTMLElement|null;if(!area||area.scrollTop<2)setCompact(false)}}} onKeyDown={e=>{if(e.key==="Home")setCompact(false)}}><h1 className="sr-only"><SiteCopy id="CartPage.1" fallback="Panier"/></h1>{!ready?<p role="status"><SiteCopy id="CartPage.2" fallback="Chargement de votre panier…"/></p>:!selected.length?<div className="catalog-empty cart-empty"><h2><SiteCopy id="CartPage.emptyTitle" fallback="Panier vide"/></h2><p><SiteCopy id="CartPage.emptyDescription" fallback="Explorez la collection pour découvrir les œuvres qui vous correspondent."/></p><Link className="button" href="/collection"><SiteCopy id="CartPage.6" fallback="Voir la collection "/></Link></div>:<div className="cart-layout"><div className="cart-selection">{selected.map(item=><article className="cart-item" key={selectionKey(item)}><Link className="artwork-image" href={"/collection/"+item.slug}><Image src={item.sculpture.image} alt={item.sculpture.imageAlt} fill sizes="(max-width:600px) 125px, 180px"/></Link><div><Link href={"/collection/"+item.slug}><h2>{item.sculpture.title}</h2></Link><p>{item.number!==undefined?t("CartPage.7","Exemplaire ")+editionName(item.sculpture,item.number)+t("CartPage.8"," / ")+item.sculpture.totalEdition:item.sculpture.editionLabel}</p><p>{formatPrice(item.sculpture.price??0)}</p><button className="remove-button" aria-label={t("CartPage.attribute.1","Retirer ")+item.sculpture.title+(item.number?", numéro "+item.number:"")} onClick={()=>remove(selectionKey(item))}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 11v6M14 11v6"/></svg></button></div></article>)}<div className="cart-total"><span><SiteCopy id="CartPage.9" fallback="Total des œuvres"/></span><strong>{formatPrice(total)}</strong></div><p className="selection-note"><SiteCopy id="CartPage.10" fallback="Livraison à définir avec l’atelier. Le panier ne réserve pas les exemplaires. La disponibilité, le montant final et les modalités d’acquisition vous seront confirmés avant tout engagement."/></p></div><div><h2 className="cart-form-title"><SiteCopy id="CartPage.11" fallback="Acquérir votre sélection."/></h2><p className="body-copy"><SiteCopy id="CartPage.12" fallback="Adressez votre sélection à l’atelier. Nous vous répondrons personnellement pour organiser la suite."/></p><InquiryForm key={items.map(selectionKey).join(",")} selection={items}/></div></div>}</main>}
