"use client";
import {SiteCopy,useCopy} from "./SiteCopy";
import {useSite} from "./SiteProvider";
import Link from "next/link";import Image from "next/image";
import {useEffect,useRef,useState,type CSSProperties} from "react";
import {type Sculpture,statusLabels,formatPrice} from "../data/sculptures";
type Placement={column?:number;span?:number};
type Arrangement={order:string[];placements:Record<string,Placement>};
const emptyArrangement:Arrangement={order:[],placements:{}};
type CatalogItem=Sculpture&{demo?:boolean;ratio?:number};
const demoFormats=[{ratio:.65,label:'Vertical',status:'available'},{ratio:1.7,label:'Panoramique',status:'available'},{ratio:1,label:'Carré',status:'available'},{ratio:.8,label:'Portrait',status:'available'},{ratio:1.45,label:'Horizontal',status:'sold'},{ratio:.58,label:'Élancé',status:'edition-complete'},{ratio:1,label:'Carré',status:'unavailable'},{ratio:1.8,label:'Panoramique',status:'exhibited'}] as const;
function MasonryGroup({items,onPreview,placements,editing,onMove}:{items:CatalogItem[];placements:Record<string,Placement>;editing:boolean;onMove:(source:string,target:string,column?:number)=>void;onPreview:(item:CatalogItem)=>void}){const grid=useRef<HTMLDivElement>(null);const [dragged,setDragged]=useState<string|null>(null),[target,setTarget]=useState<string|null>(null);const drop=useRef<{slug:string;column:number}|null>(null);useEffect(()=>{const node=grid.current;if(!node)return;const cards=[...node.querySelectorAll<HTMLElement>('.masonry-card')];let scheduled=0;function layout(){const width=node!.clientWidth;const columns=width<500?1:width<850?2:width<1150?3:4;const gap=16,unit=(width-gap*(columns-1))/columns,heights=Array(columns).fill(0);node!.style.setProperty('--grid-step',(unit+gap)+'px');node!.dataset.columns=String(columns);cards.forEach(card=>{const preference=placements[card.dataset.slug??''];const span=Math.min(columns,preference?.span??(card.dataset.wide==='true'?2:1));card.style.width=(unit*span+gap*(span-1))+'px';let best=0,top=Infinity;for(let c=0;c<=columns-span;c++){const y=Math.max(...heights.slice(c,c+span));if(y<top){top=y;best=c}}if(preference?.column!==undefined){best=Math.min(columns-span,Math.max(0,preference.column));top=Math.max(...heights.slice(best,best+span))}card.style.left=(best*(unit+gap))+'px';card.style.top=top+'px';const bottom=top+card.offsetHeight+gap;for(let c=best;c<best+span;c++)heights[c]=bottom;card.dataset.measured='true'});node!.style.height=Math.max(0,Math.max(...heights)-gap)+'px'}function schedule(){cancelAnimationFrame(scheduled);scheduled=requestAnimationFrame(layout)}const observer=new ResizeObserver(schedule);observer.observe(node);cards.forEach(card=>observer.observe(card.firstElementChild!));layout();const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)(entry.target as HTMLElement).dataset.visible='true'}),{root:node.closest('.catalog-viewport'),threshold:.05});cards.forEach(card=>reveal.observe(card.firstElementChild!));return()=>{cancelAnimationFrame(scheduled);observer.disconnect();reveal.disconnect()}},[items,placements]);function clear(){setDragged(null);setTarget(null);drop.current=null}
function locate(event:React.DragEvent<HTMLDivElement>){if(!dragged||!grid.current)return;event.preventDefault();event.dataTransfer.dropEffect='move';const node=grid.current,box=node.getBoundingClientRect(),columns=Number(node.dataset.columns)||1;const column=Math.max(0,Math.min(columns-1,Math.floor((event.clientX-box.left)/((box.width+16)/columns))));const source=items.find(item=>item.slug===dragged);const available=(item:CatalogItem)=>item.status==='available'||item.status==='made-to-order';const candidates=[...node.querySelectorAll<HTMLElement>('.masonry-card')].filter(card=>{const item=items.find(i=>i.slug===card.dataset.slug);return item&&source&&available(item)===available(source)});let nearest:HTMLElement|undefined,distance=Infinity;for(const card of candidates){const r=card.getBoundingClientRect();const dx=Math.max(r.left-event.clientX,0,event.clientX-r.right),dy=Math.max(r.top-event.clientY,0,event.clientY-r.bottom);const d=dx*dx+dy*dy;if(d<distance){distance=d;nearest=card}}if(nearest){drop.current={slug:nearest.dataset.slug!,column};setTarget(nearest.dataset.slug!)}const viewport=node.closest('.catalog-viewport') as HTMLElement;if(viewport){const r=viewport.getBoundingClientRect();if(event.clientY<r.top+65)viewport.scrollTop-=22;else if(event.clientY>r.bottom-65)viewport.scrollTop+=22}}
return <div ref={grid} className="masonry-grid packed-masonry" data-editing={editing} data-dragging={!!dragged} onDragOver={locate} onDrop={e=>{if(!dragged)return;e.preventDefault();if(drop.current)onMove(dragged,drop.current.slug,drop.current.column);clear()}} onDragEnd={clear}>{items.map(item=><MasonryCard key={item.slug} item={item} onPreview={onPreview} editing={editing} dragging={dragged===item.slug} target={target===item.slug} onStart={e=>{setDragged(item.slug);setTarget(item.slug);drop.current=null;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',item.slug);e.dataTransfer.setDragImage(e.currentTarget,Math.min(80,e.currentTarget.clientWidth/2),45)}} onKeyMove={delta=>{const group=items.filter(candidate=>(candidate.status==='available'||candidate.status==='made-to-order')===(item.status==='available'||item.status==='made-to-order'));const index=group.findIndex(candidate=>candidate.slug===item.slug),neighbor=group[index+delta];if(neighbor)onMove(item.slug,neighbor.slug)}}/>)}</div>}
function MasonryCard({item,onPreview,editing,dragging,target,onStart,onKeyMove}:{item:CatalogItem;onPreview:(item:CatalogItem)=>void;editing:boolean;dragging:boolean;target:boolean;onStart:(e:React.DragEvent<HTMLElement>)=>void;onKeyMove:(delta:number)=>void}){const t=useCopy();const [ratio,setRatio]=useState(item.ratio??1);const content=<><div className="masonry-image" style={{aspectRatio:ratio}}><Image draggable={false} src={item.image} alt={item.imageAlt} fill sizes="(max-width:600px) 90vw, (max-width:1000px) 45vw, 30vw" style={{objectFit:item.demo?'cover':'contain'}} onLoad={e=>{if(!item.demo&&e.currentTarget.naturalHeight)setRatio(e.currentTarget.naturalWidth/e.currentTarget.naturalHeight)}}/>{item.demo&&<span className="image-note"><SiteCopy id="Catalog.1" fallback="Maquette de format"/></span>}</div><div className="masonry-caption"><h2>{item.title}</h2><p>{item.demo?t("Catalog.2","Exemple de présentation · non commercialisé"):item.editionLabel}</p><div className="masonry-meta"><span className="availability" data-status={item.status}>{t('status.'+item.status,statusLabels[item.status])}</span>{!item.demo&&<span>{item.price===null?t("Catalog.3","Sur demande"):formatPrice(item.price)}</span>}</div></div></>;
return <article className="masonry-card" draggable={editing} tabIndex={editing?0:undefined} aria-label={editing?t("Catalog.attribute.1","Déplacer ")+item.title:undefined} aria-describedby={editing?'drag-instructions':undefined} data-drag-source={dragging} data-drop-target={target} onDragStart={onStart} onKeyDown={e=>{if(!editing)return;if(e.key==='ArrowLeft'||e.key==='ArrowUp'){e.preventDefault();onKeyMove(-1)}else if(e.key==='ArrowRight'||e.key==='ArrowDown'){e.preventDefault();onKeyMove(1)}}} data-slug={item.slug} data-wide={ratio>1.4}><div className="masonry-inner">{editing?<div className="masonry-link">{content}<span className="drag-grip" aria-hidden="true"><SiteCopy id="Catalog.4" fallback="⠿"/></span></div>:item.demo?<button className="masonry-link" type="button" onClick={()=>onPreview(item)}>{content}</button>:<Link className="masonry-link" href={'/collection/'+item.slug}>{content}</Link>}</div></article>}
export function Catalog({items}:{items:Sculpture[]}){const t=useCopy();const {content,admin,save}=useSite();const [saveError,setSaveError]=useState(''),[saving,setSaving]=useState(false);const [demos,setDemos]=useState(false),[preview,setPreview]=useState<CatalogItem|null>(null);const [editing,setEditing]=useState(false);const arrangement=content.catalogLayout;
const local=admin;
async function update(next:Arrangement){if(!admin||saving)return;setSaving(true);setSaveError('');try{await save({...content,catalogLayout:next})}catch(e){setSaveError(e instanceof Error?e.message:'Enregistrement impossible.')}finally{setSaving(false)}}
const dialog=useRef<HTMLDialogElement>(null);const samples:CatalogItem[]=items.length?demoFormats.map((format,i)=>({...items[i%items.length],slug:'demo-'+i,title:'Étude de format — '+format.label,status:format.status,ratio:format.ratio,demo:true,price:null,imageAlt:'Maquette de présentation '+format.label+', image provisoire réutilisée'})):[];const all:CatalogItem[]=[...items,...(demos?samples:[])];const available=all.filter(item=>item.status==='available'||item.status==='made-to-order');const archived=all.filter(item=>item.status!=='available'&&item.status!=='made-to-order');const rank=(slug:string)=>{const index=arrangement.order.indexOf(slug);return index<0?10000:index};const ordered=[...available.sort((a,b)=>rank(a.slug)-rank(b.slug)),...archived.sort((a,b)=>rank(a.slug)-rank(b.slug))];function move(source:string,target:string,column?:number){const order=ordered.map(item=>item.slug),from=order.indexOf(source),to=order.indexOf(target);if(from<0||to<0)return;order.splice(from,1);order.splice(to,0,source);const placements={...arrangement.placements};if(column===undefined)delete placements[source];else placements[source]={column};update({order,placements})}
function show(item:CatalogItem){setPreview(item);dialog.current?.showModal()}
return <><div className="catalog-toolbar">{local&&<button className="button" aria-expanded={editing} onClick={()=>setEditing(!editing)}>{editing?t("Catalog.5","Fermer la grille"):t("Catalog.6","Composer la grille")}</button>}{admin&&<button className="button" onClick={()=>setDemos(!demos)} aria-pressed={demos}>{demos?t("Catalog.7","Masquer les maquettes"):t("Catalog.8","Afficher les maquettes")}</button>}</div>{editing&&<div className="drag-toolbar"><p id="drag-instructions"><SiteCopy id="Catalog.9" fallback="Glissez une œuvre, puis relâchez pour la placer. Au clavier : utilisez les flèches."/></p><button className="button" onClick={()=>update(emptyArrangement)}><SiteCopy id="Catalog.10" fallback="Réinitialiser"/></button></div>}{saveError&&<p role="alert">{saveError}</p>}{saving&&<p role="status"><SiteCopy id="Catalog.11" fallback="Enregistrement…"/></p>}<div className="catalog-viewport" tabIndex={0} role="region" aria-label={t("Catalog.12","Catalogue des sculptures, défilement vertical")}><MasonryGroup key={String(editing)} items={ordered} placements={arrangement.placements} editing={editing} onMove={move} onPreview={show}/></div><dialog ref={dialog} className="demo-dialog" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><button className="button" onClick={()=>dialog.current?.close()}><SiteCopy id="Catalog.13" fallback="Fermer"/></button>{preview&&<><h2>{preview.title}</h2><p><SiteCopy id="Catalog.14" fallback="Maquette temporaire pour visualiser le catalogue. Ce visuel ne correspond pas à une nouvelle œuvre et ne peut pas être acheté."/></p><div className="demo-preview" style={{aspectRatio:preview.ratio} as CSSProperties}><Image src={preview.image} alt={preview.imageAlt} fill sizes="70vw" style={{objectFit:'cover'}}/></div></>}</dialog></>}
