"use client";
import {LiquidSelect} from "./LiquidSelect";
import {useState} from 'react';import {EditionScroller} from './EditionScroller';import {type Sculpture} from '../data/sculptures';
const greek=['α','β','γ','δ','ε','ζ','η','θ','ι','κ','λ','μ','ν','ξ','ο','π','ρ','σ','τ','υ','φ','χ','ψ','ω'];
export function EditionAdmin({sculpture,onChange}:{sculpture:Sculpture;onChange:(change:Partial<Sculpture>)=>void}){
 const [quantity,setQuantity]=useState(sculpture.totalEdition??1),[style,setStyle]=useState('numbers'),[selected,setSelected]=useState(1),[notice,setNotice]=useState('');
 const ids=Array.from({length:sculpture.totalEdition??1},(_,i)=>i+1),names=sculpture.editionNames??{};
 function create(){if(!Number.isInteger(quantity)||quantity<1||quantity>10000)return;const numbers=Array.from({length:quantity},(_,i)=>i+1);if(quantity<(sculpture.totalEdition??0)&&!confirm('Réduire le nombre d’exemplaires et retirer ceux au-delà de '+quantity+' ?'))return;const labels:Record<string,string>={};if(style==='greek')numbers.forEach((n,i)=>labels[String(n)]=greek[i%24]+(i>=24?String(Math.floor(i/24)+1):''));onChange({totalEdition:quantity,availableNumbers:numbers,editionNames:labels});setSelected(1);setNotice('Tous les exemplaires sont sélectionnés. Cliquez sur ceux à rendre indisponibles.')}
 return <div className="edition-admin"><div className="edition-admin-controls"><label>Nombre d’exemplaires<input type="number" min="1" max="10000" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>Libellés<LiquidSelect value={style} onChange={e=>setStyle(e.target.value)}><option value="numbers">01, 02, 03…</option><option value="greek">α, β, γ…</option></LiquidSelect></label><button type="button" className="button" onClick={create}>Appliquer</button></div><p>Cliquez sur un exemplaire pour changer sa disponibilité. Les libellés peuvent être personnalisés ci-dessous.</p><EditionScroller numbers={ids} values={sculpture.availableNumbers??[]} labels={names} total={sculpture.totalEdition} onChange={n=>{const available=sculpture.availableNumbers??[];onChange({availableNumbers:available.includes(n)?available.filter(v=>v!==n):[...available,n].sort((a,b)=>a-b)});setSelected(n)}}/><div className="edition-admin-actions"><button className="button" onClick={()=>onChange({availableNumbers:ids})}>Tout sélectionner</button><button className="button" onClick={()=>onChange({availableNumbers:[]})}>Tout désélectionner</button></div><div className="edition-admin-controls"><label>Exemplaire à renommer<LiquidSelect value={selected} onChange={e=>setSelected(Number(e.target.value))}>{ids.map(n=><option key={n} value={n}>{names[String(n)]||String(n).padStart(2,'0')}</option>)}</LiquidSelect></label><label>Nom affiché (ex. α, gamma)<input maxLength={40} value={names[String(selected)]??''} placeholder={String(selected).padStart(2,'0')} onChange={e=>{const next={...names};if(e.target.value.trim())next[String(selected)]=e.target.value;else delete next[String(selected)];onChange({editionNames:next})}}/></label></div><p role="status">{notice}</p></div>
}
