"use client";
import {SiteCopy,useCopy} from "./SiteCopy";
import {useEffect,useRef} from "react";
export function EditionScroller({numbers,total,values,onChange,labels}:{numbers:number[];total?:number;labels?:Record<string,string>;values:number[];onChange:(n:number)=>void}){const t=useCopy();
 const rail=useRef<HTMLDivElement>(null);const speed=useRef(0);const frame=useRef(0);const last=useRef(0);
 function stop(){speed.current=0;cancelAnimationFrame(frame.current);frame.current=0;last.current=0;}
 function animate(time:number){const node=rail.current;if(!node||!speed.current){frame.current=0;return;}const dt=last.current?Math.min(time-last.current,40):16;node.scrollLeft+=speed.current*dt*.4;last.current=time;frame.current=requestAnimationFrame(animate);}
 useEffect(()=>{const node=rail.current;if(!node)return;const wheel=(event:WheelEvent)=>{if(node.scrollWidth<=node.clientWidth)return;event.preventDefault();node.scrollLeft+=Math.abs(event.deltaX)>Math.abs(event.deltaY)?event.deltaX:event.deltaY;};node.addEventListener('wheel',wheel,{passive:false});return()=>{node.removeEventListener('wheel',wheel);cancelAnimationFrame(frame.current)};},[]);
 return <div className="edition-picker"><div className="edition-heading"><span><SiteCopy id="EditionScroller.1" fallback="Numéro d’édition"/></span><span aria-live="polite">{values.length===0?t("EditionScroller.2","Choisir un ou plusieurs exemplaires"):values.length===1?(labels?.[String(values[0])]||String(values[0]).padStart(2,'0'))+(total?' / '+total:''):values.length+t("EditionScroller.3"," exemplaires sélectionnés")}</span></div><div ref={rail} className="edition-rail" role="group" aria-label={t("EditionScroller.4","Numéros d’édition disponibles")} onPointerMove={event=>{if(event.pointerType!=='mouse'||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const box=event.currentTarget.getBoundingClientRect();const x=(event.clientX-box.left)/box.width;speed.current=x<.22?-((.22-x)/.22):x>.78?(x-.78)/.22:0;if(!speed.current){stop();return;}if(!frame.current)frame.current=requestAnimationFrame(animate)}} onPointerLeave={stop} onPointerDown={stop} onKeyDown={e=>{const target=e.target as HTMLButtonElement;const index=numbers.indexOf(Number(target.value));if(index<0)return;let next=index;if(e.key==='ArrowRight')next=Math.min(numbers.length-1,index+1);else if(e.key==='ArrowLeft')next=Math.max(0,index-1);else if(e.key==='Home')next=0;else if(e.key==='End')next=numbers.length-1;else return;e.preventDefault();const button=rail.current?.querySelectorAll('button')[next] as HTMLButtonElement|undefined;button?.focus();button?.scrollIntoView({block:'nearest',inline:'nearest'});}}>{numbers.map(n=><button key={n} type="button" value={n} aria-label={t("EditionScroller.attribute.1","Exemplaire ")+(labels?.[String(n)]||n)} aria-pressed={values.includes(n)} onClick={()=>{stop();onChange(n)}} onFocus={stop}>{labels?.[String(n)]||String(n).padStart(2,'0')}</button>)}</div></div>;
}
