"use client";
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {textBlocks,type TextPage,type TextDevice,type TextLayout,type TextPosition} from '../data/text-layout';
import type {SiteContent} from '../data/content';
export function TextCanvas({texts,page,device,layout,editing,onMove,onSelect,selected,title}:{texts:SiteContent['texts'];page:TextPage;device:TextDevice;layout?:TextLayout;editing?:boolean;onMove?:(id:string,p:TextPosition)=>void;onSelect?:(id:string)=>void;selected?:string;title?:ReactNode}){
 const root=useRef<HTMLDivElement>(null),drag=useRef<{id:string;x:number;y:number;p:TextPosition;scale:number;width:number}|null>(null);
 useEffect(()=>{const node=root.current;if(!node||!layout)return;const measure=()=>{let bottom=layout.height;node.querySelectorAll<HTMLElement>('[data-text-block]').forEach(el=>{bottom=Math.max(bottom,el.offsetTop+el.offsetHeight+20)});node.style.minHeight=bottom+'px'};const observer=new ResizeObserver(measure);node.querySelectorAll('[data-text-block]').forEach(el=>observer.observe(el));measure();return()=>observer.disconnect()},[layout,texts]);
 return <div ref={root} className="free-text-canvas" data-device={device} data-custom={!!layout} data-editing={!!editing} style={layout?{minHeight:layout.height}:undefined}>{textBlocks(texts,page).map(block=>{const p=layout?.positions[block.id];const Tag=block.title?'h1':'p';return <Tag key={block.id} data-text-block={block.id} data-copy-key={'text:'+block.key} data-selected={selected===block.id} className={block.intro||page==='sur-mesure'&&!block.title?'body-copy':undefined} style={p?{position:'absolute',left:p.x+'%',top:p.y,width:p.width+'%',margin:0}:undefined} tabIndex={editing?0:undefined}
 onFocus={()=>onSelect?.(block.id)} onPointerDown={e=>{if(!editing||!p||!root.current)return;e.preventDefault();onSelect?.(block.id);e.currentTarget.setPointerCapture(e.pointerId);const rect=root.current.getBoundingClientRect();drag.current={id:block.id,x:e.clientX,y:e.clientY,p,scale:rect.width/root.current.clientWidth,width:rect.width}}}
 onPointerMove={e=>{const d=drag.current;if(!d||!editing)return;onMove?.(d.id,{...d.p,x:Math.max(0,Math.min(100-d.p.width,d.p.x+(e.clientX-d.x)/d.width*100)),y:Math.max(0,Math.min(1800,d.p.y+(e.clientY-d.y)/d.scale))})}}
 onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{const d=drag.current;if(d)onMove?.(d.id,d.p);drag.current=null}}
 onKeyDown={e=>{if(!editing||!p||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const step=e.shiftKey?10:2;onMove?.(block.id,{...p,x:Math.max(0,Math.min(100-p.width,p.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0))),y:Math.max(0,Math.min(1800,p.y+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0)))})}}>{block.title&&title?title:block.text}</Tag>})}</div>;
}
export function FreeText({content,page,title}:{content:SiteContent;page:TextPage;title?:ReactNode}){const [device,setDevice]=useState<TextDevice>('desktop');useEffect(()=>{const phone=matchMedia('(max-width:767px)'),tablet=matchMedia('(max-width:1199px)'),coarse=matchMedia('(pointer:coarse)');const update=()=>setDevice(phone.matches?'phone':tablet.matches||coarse.matches?'tablet':'desktop');update();const queries=[phone,tablet,coarse];queries.forEach(q=>q.addEventListener('change',update));return()=>queries.forEach(q=>q.removeEventListener('change',update))},[]);return <TextCanvas texts={content.texts} page={page} device={device} layout={content.textLayouts?.[page]?.[device]} title={title}/>}
