"use client";
import {LiquidSelect} from "./LiquidSelect";
import Image from 'next/image';import {useState} from 'react';import {useSite} from './SiteProvider';
type Photo={src:string;alt:string;format?:'original'|'square'|'vertical'|'horizontal'};
const formats={original:'Format original',square:'Carré · 1:1',vertical:'Vertical · 2:3',horizontal:'Horizontal · 3:2'};
export function HomeSidePhotos({slug,photos,space,mainWidth,visible}:{slug:string;photos:Photo[];space:{width:number;height:number};mainWidth:number;visible:boolean}){
 const {content,admin,preview,save}=useSite();const [editing,setEditing]=useState(false),[ratios,setRatios]=useState<Record<string,number>>({}),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const items=photos.slice(0,6).map((photo,index)=>({...photo,index,ratio:photo.format==='square'?1:photo.format==='vertical'?2/3:photo.format==='horizontal'?1.5:ratios[photo.src]??1}));
 const sides:[typeof items,typeof items]=[[],[]],heights=[0,0];for(const item of items){const side=sides[0].length>=3?1:sides[1].length>=3?0:heights[0]<=heights[1]?0:1;sides[side].push(item);heights[side]+=1/item.ratio}
 const railWidth=Math.max(0,Math.min(space.width*.23,(space.width-mainWidth)/2-16)),railHeight=Math.max(0,space.height-42),edge=18;
 async function change(index:number,format:Photo['format']){if(saving)return;setSaving(true);try{await save({...content,sculptures:content.sculptures.map(s=>s.slug===slug?{...s,photos:(s.photos?.length?s.photos:photos).map((p,i)=>i===index?{...p,format}:p)}:s)});setMessage(preview?'Format modifié dans l’aperçu.':'Format enregistré.')}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
 return <div className="automatic-side-photos" data-visible={visible||editing} data-editing={editing} onWheelCapture={e=>{if(editing)e.stopPropagation()}} onKeyDown={e=>{if(editing)e.stopPropagation()}}>
 {admin&&<div className="side-editor-toolbar"><button className="button" onClick={()=>setEditing(!editing)}>{editing?'Terminer':'Formats des photos'}</button>{editing&&<span role="status">{message||'6 photos maximum · placement automatique'}</span>}</div>}
 {sides.map((items,side)=>{const desired=items.map(p=>(railWidth-edge)/p.ratio+edge),total=desired.reduce((a,b)=>a+b,0),scale=Math.min(1,Math.max(0,railHeight-16*Math.max(0,items.length-1))/Math.max(1,total));return <div className="automatic-photo-rail" style={{width:railWidth}} key={side} data-side={side}>{items.map((p,i)=>{const h=Math.max(edge,desired[i]*scale),w=(h-edge)*p.ratio+edge;return <div key={p.index} className="automatic-photo-entry" style={{width:w,height:h}}><div className="side-photo-frame" style={{width:w,height:h}}><div>{w>edge&&h>edge&&<Image src={p.src} alt={p.alt} fill loading="eager" sizes="24vw" style={{objectFit:p.format&&p.format!=='original'?'cover':'contain'}} onLoad={e=>{const img=e.currentTarget;if(img.naturalHeight){const ratio=img.naturalWidth/img.naturalHeight;setRatios(current=>current[p.src]===ratio?current:{...current,[p.src]:ratio})}}}/>}</div></div>{editing&&<label className="auto-format-label">Photo {p.index+1}<LiquidSelect disabled={saving} value={p.format??'original'} onChange={e=>void change(p.index,e.target.value as Photo['format'])}>{Object.entries(formats).map(([value,label])=><option key={value} value={value}>{label}</option>)}</LiquidSelect></label>}</div>})}</div>})}
 </div>
}
