"use client";
import {useCallback,useEffect,useState} from 'react';
import {LiquidSelect} from './LiquidSelect';
import type {ContactRequest,ContactStatus} from '../lib/contact-store.mjs';
const statuses:Record<ContactStatus,string>={received:'Reçue',replied:'Répondue','in-progress':'En cours',completed:'Terminée'};
export function RequestInbox(){
 const [items,setItems]=useState<ContactRequest[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('all');
 const refresh=useCallback(async()=>{setBusy(true);setError('');try{const r=await fetch('/api/admin/requests',{cache:'no-store'});if(!r.ok)throw Error('Impossible de charger les demandes. Vérifiez votre connexion.');setItems(await r.json())}catch(e){setError((e as Error).message)}finally{setBusy(false)}},[]);
 useEffect(()=>{let active=true;fetch('/api/admin/requests',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('Impossible de charger les demandes.');return r.json()}).then(data=>{if(active)setItems(data)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[]);
 async function change(id:string,status:ContactStatus){setBusy(true);setError('');try{const r=await fetch('/api/admin/requests',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});if(!r.ok)throw Error('État non enregistré. Réessayez.');setItems(await r.json())}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const visible=items.filter(item=>filter==='all'||item.status===filter);
 return <section className="request-inbox"><header><h2>Demandes</h2><button type="button" className="button" disabled={busy} onClick={()=>void refresh()}>Actualiser</button></header><p>Les nouvelles demandes apparaissent ici, de la plus récente à la plus ancienne. Les états sont enregistrés immédiatement.</p><p>Après avoir répondu par e-mail, choisissez « Répondue ». Cela autorise le client à vous écrire à nouveau. Aucun e-mail n’est envoyé par ce bouton.</p><label>Afficher<LiquidSelect value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Toutes les demandes</option>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</LiquidSelect></label>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Chargement…</p>}{!busy&&!error&&!visible.length&&<p>Aucune demande dans cette vue. Les anciens messages restent dans votre boîte mail.</p>}<div className="request-list">{visible.map(item=><article className="request-card" key={item.id}><header><h3>{item.details.acquisition?'Acquisition':'Sur mesure'} · {item.details.firstName} {item.details.lastName}</h3><time dateTime={item.createdAt}>{new Date(item.createdAt).toLocaleString('fr-FR')}</time></header>{item.ownerTest&&<p>Test depuis un appareil autorisé</p>}{item.delivery!=='sent'&&<p role="status">Envoi non confirmé : vérifiez votre boîte mail avant toute action.</p>}<div className="request-contact"><a className="button" href={'mailto:'+item.details.email}>Écrire à {item.details.email}</a><a className="button" href={'tel:'+item.details.phone}>{item.details.phone}</a></div><p className="request-message">{item.details.message}</p>{item.details.artworks.length>0&&<ul>{item.details.artworks.map((line,i)=><li key={i}>{line}</li>)}</ul>}{!item.details.acquisition&&item.details.dimensions&&<p>Dimensions : {item.details.dimensions}</p>}<label>État de la demande<LiquidSelect disabled={busy} value={item.status} onChange={e=>void change(item.id,e.target.value as ContactStatus)}>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</LiquidSelect></label></article>)}</div></section>
}
