import {validateTextLayouts} from '../data/text-layout';
import {validateTranslations} from '../data/localized-content';
import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';import path from 'node:path';import {randomUUID} from 'node:crypto';import {initialContent,type SiteContent} from '../data/content';import {statusLabels} from '../data/sculptures';
export const cmsDir=path.join(process.cwd(),'.arxylve-private','cms');
export async function readJson<T>(name:string,fallback:T):Promise<T>{try{return JSON.parse(await readFile(path.join(/*turbopackIgnore: true*/ cmsDir,name),'utf8'))}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return fallback;throw e}}
export async function atomicJson(name:string,value:unknown){await mkdir(cmsDir,{recursive:true});const target=path.join(/*turbopackIgnore: true*/ cmsDir,name),temp=target+'.'+randomUUID()+'.tmp';await writeFile(temp,JSON.stringify(value,null,2),{mode:0o600});await rename(temp,target)}
export async function readContent(){const saved=await readJson<SiteContent>('content.json',initialContent);return {...saved,texts:{...initialContent.texts,...saved.texts}}}
export const mediaPath=(value:unknown)=>typeof value==='string'&&/^\/(?:images\/[a-zA-Z0-9_./-]+|media\/[a-f0-9-]+\.(?:jpg|png|webp|mp4|webm))$/.test(value)&&!value.includes('..');
export function validateContent(value:unknown):asserts value is SiteContent{const c=value as SiteContent;validateTranslations(c?.translations);validateTextLayouts(c?.textLayouts);if(!c||!Array.isArray(c.sculptures)||c.sculptures.length>500||!c.texts||!c.homeLayouts||!c.catalogLayout)throw Error('Contenu invalide.');if(c.copy&&(typeof c.copy!=='object'||Array.isArray(c.copy)||Object.keys(c.copy).length>3000||Object.entries(c.copy).some(([key,text])=>key.length>240||typeof text!=='string'||text.length>20000)))throw Error('Textes personnalisés invalides.');const slugs=new Set<string>();for(const s of c.sculptures){if(!s||!/^([a-z0-9]+-)*[a-z0-9]+$/.test(s.slug)||slugs.has(s.slug))throw Error('Chaque œuvre doit avoir un identifiant unique.');slugs.add(s.slug);for(const key of ['title','description','material','dimensions','imageAlt','editionLabel'] as const)if(typeof s[key]!=='string'||s[key].length>10000)throw Error('Texte d’œuvre invalide.');if(!s.title.trim()||!mediaPath(s.image)||!(s.status in statusLabels)||!['limited-numbered','unique','continuous-series','made-to-order','prototype','exhibition-piece'].includes(s.editionType)||!(s.price===null||(Number.isFinite(s.price)&&s.price>=0)))throw Error('Vérifiez le prix, le statut et l’image.');if(s.editionType==='limited-numbered'&&(!Number.isInteger(s.totalEdition)||s.totalEdition!<1||s.totalEdition!>10000))throw Error('Nombre total d’éditions invalide.');if(s.availableNumbers&&(!Array.isArray(s.availableNumbers)||new Set(s.availableNumbers).size!==s.availableNumbers.length||s.availableNumbers.some(n=>!Number.isInteger(n)||n<1||n>(s.totalEdition??10000))))throw Error('Numéros d’édition invalides.');if(s.editionNames){if(typeof s.editionNames!=='object'||Array.isArray(s.editionNames)||Object.entries(s.editionNames).some(([key,name])=>!/^\d+$/.test(key)||Number(key)<1||Number(key)>(s.totalEdition??10000)||typeof name!=='string'||!name.trim()||name.length>40||/[\u0000-\u001f]/.test(name)))throw Error('Libellés d’édition invalides.');const names=Array.from({length:s.totalEdition??0},(_,i)=>s.editionNames?.[String(i+1)]||String(i+1).padStart(2,'0'));if(new Set(names.map(v=>v.normalize('NFC').trim())).size!==names.length)throw Error('Les exemplaires doivent avoir des libellés différents.');}if(s.photos&&(!Array.isArray(s.photos)||s.photos.length>24||s.photos.some(p=>!mediaPath(p.src)||typeof p.alt!=='string'||(p.format!==undefined&&!['original','square','vertical','horizontal'].includes(p.format)))))throw Error('Photographies invalides.');if(s.videos&&(!Array.isArray(s.videos)||s.videos.length>12||s.videos.some(p=>!mediaPath(p.src)||!/^\/media\/.+\.(mp4|webm)$/.test(p.src)||typeof p.alt!=='string')))throw Error('Vidéos invalides.')}
if(c.aboutPhotos&&(!Array.isArray(c.aboutPhotos)||c.aboutPhotos.length>24||c.aboutPhotos.some(p=>!mediaPath(p.src)||typeof p.alt!=='string'||p.alt.length>200)))throw Error('Photos du diaporama invalides.');for(const key of Object.keys(initialContent.texts) as (keyof SiteContent['texts'])[])if(typeof c.texts[key]!=='string'||c.texts[key].length>20000)throw Error('Texte de page invalide.');if(!mediaPath(c.texts.aboutPortrait))throw Error('Portrait invalide.');
if(!Array.isArray(c.catalogLayout.order)||new Set(c.catalogLayout.order).size!==c.catalogLayout.order.length||c.catalogLayout.order.some(v=>typeof v!=='string')||!c.catalogLayout.placements)throw Error('Grille invalide.');for(const p of Object.values(c.catalogLayout.placements))if(!p||(p.column!==undefined&&(!Number.isInteger(p.column)||p.column<0||p.column>3))||(p.span!==undefined&&![1,2].includes(p.span)))throw Error('Placement invalide.');
for(const positions of Object.values(c.homeLayouts)){if(!Array.isArray(positions)||positions.length>24)throw Error('Grille photo invalide.');const occupied=new Set<number>();for(const p of positions){if(!p||!Number.isInteger(p.slot)||p.slot<0||p.slot>23||![1,2].includes(p.w)||!Number.isInteger(p.h)||p.h<1||p.h>6||(p.slot%2)+p.w>2||Math.floor(p.slot%12/2)+p.h>6)throw Error('Photo en dehors de la grille.');for(let y=0;y<p.h;y++)for(let x=0;x<p.w;x++){const cell=p.slot+y*2+x;if(occupied.has(cell))throw Error('Deux photos se chevauchent.');occupied.add(cell)}}}}
let queue=Promise.resolve();export function saveContent(next:SiteContent){const job=queue.then(async()=>{const current=await readContent();if(next.revision!==current.revision)throw Error('Le contenu a changé dans une autre fenêtre. Rechargez avant de réessayer.');validateContent(next);await atomicJson('content-backup.json',current);const updated={...next,revision:current.revision+1};await atomicJson('content.json',updated);return updated});queue=job.then(()=>{},()=>{});return job}
